name: "Reusable Unix Build"

on:
  workflow_call:
    inputs:
      create-setup:
        description: 'Whether to create Debian setup installer'
        required: false
        type: boolean
        default: false
      build-type:
        description: 'Build type (Debug or Release)'
        required: false
        type: string
        default: 'Release'

jobs:
  buildUnix:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - run: mkdir ${{github.workspace}}/build

    - name: Install other dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build libgtk-3-dev ccache
        gcc --version
        cmake --version
        ccache --version

    - name: Setup ccache
      run: |
        ccache --set-config=cache_dir=${{runner.workspace}}/.ccache
        ccache --set-config=compression=true
        ccache --set-config=sloppiness=pch_defines,time_macros,include_file_mtime,include_file_ctime
        ccache --set-config=hard_link=true
        ccache --zero-stats
        ccache --show-config

    - name: Cache ccache
      uses: actions/cache@v4
      with:
        path: ${{runner.workspace}}/.ccache
        key: ${{ runner.os }}-ccache-${{ github.ref_name }}-${{ github.run_number }}
        restore-keys: |
          ${{ runner.os }}-ccache-${{ github.ref_name }}-
          ${{ runner.os }}-ccache-
        enableCrossOsArchive: false
        save-always: true

    - name: Cache CMake FetchContent
      uses: actions/cache@v4
      with:
        path: |
          ${{github.workspace}}/build/_deps
        key: ${{ runner.os }}-fetchcontent-${{ hashFiles('**/CMakeLists.txt', 'CMakePresets.json') }}
        restore-keys: |
          ${{ runner.os }}-fetchcontent-
        enableCrossOsArchive: false
        save-always: true

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{inputs.build-type}}

    - name: Build wxUiEditor
      run: cmake --build ${{github.workspace}}/build --config ${{inputs.build-type}} --target wxUiEditor

    - name: Show ccache statistics
      run: ccache --show-stats

    - name: Build Setup
      if: ${{ inputs.create-setup }}
      run: |
        cd build
        cpack -G DEB -C ${{inputs.build-type}}

    - name: Create Debian Artifact
      if: ${{ inputs.create-setup }}
      uses: actions/upload-artifact@v4
      with:
        name: DebianSetup
        path: |
          build/wxUiEditor-*-Linux.deb
